"""Drop post

Revision ID: 09013c8508cc
Revises: 0b1275282919
Create Date: 2020-08-12 12:54:12.947693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09013c8508cc'
down_revision = '0b1275282919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('Content', sa.VARCHAR(length=300), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
